name: CI-CD

on:
  push:
    branches: [ development ]

# Set env variables
env:
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: 'secure-forest-32038'
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 17.x

      - name: install dependencies      
        run: |
          npm install
          npm ci

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - run: npm run test
  